// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("6015c1b7-794d-4c2e-a54b-416a5e03c827"),
	Geocodio("cd9b30fe-b9fd-468d-bbb3-775d428c1999"),
	LocationIQ("826448f7-1dba-42d6-9cc8-8d30a188ecf8"),
	MapQuest("6396ecd7-bafa-4960-b362-1c196dd514f8");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
