// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("70c2db81-b6d8-4a08-ba60-d61bbb314f8d"),
	Geocodio("a09e53c6-92c4-4bb3-8370-1bbcd012aca8"),
	LocationIQ("ab0a6382-b001-4b8a-8cbd-2b3d2ef2ef02"),
	MapQuest("0527aa06-3858-4fa1-9429-711f75972e0c");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
