// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("b7fba527-b01e-44f7-ad48-8e5f82530bd8"),
	Geocodio("e5b0e452-ebcc-45de-959b-cc6f6663218b"),
	LocationIQ("a5a9f0b5-86d3-4927-98d1-1270c31e434b"),
	MapQuest("dd1ce7d5-a382-4a43-bb30-bb2c17bcb265");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
