// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public class CdcSnapshotStore implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cdcSnapshotStoreMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.CdcSnapshotStore";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		entity("entity"),
		topic("topic");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CdcSnapshotStore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CdcSnapshotStore(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cdcSnapshotStoreMendixObject)
	{
		if (cdcSnapshotStoreMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!cdcSnapshotStoreMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cdcSnapshotStoreMendixObject = cdcSnapshotStoreMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static system.proxies.CdcSnapshotStore initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.CdcSnapshotStore(context, mendixObject);
	}

	public static system.proxies.CdcSnapshotStore load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.CdcSnapshotStore.initialize(context, mendixObject);
	}

	public static java.util.List<system.proxies.CdcSnapshotStore> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> system.proxies.CdcSnapshotStore.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of entity
	 */
	public final java.lang.String getentity()
	{
		return getentity(getContext());
	}

	/**
	 * @param context
	 * @return value of entity
	 */
	public final java.lang.String getentity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.entity.toString());
	}

	/**
	 * Set value of entity
	 * @param entity
	 */
	public final void setentity(java.lang.String entity)
	{
		setentity(getContext(), entity);
	}

	/**
	 * Set value of entity
	 * @param context
	 * @param entity
	 */
	public final void setentity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entity)
	{
		getMendixObject().setValue(context, MemberNames.entity.toString(), entity);
	}

	/**
	 * @return value of topic
	 */
	public final java.lang.String gettopic()
	{
		return gettopic(getContext());
	}

	/**
	 * @param context
	 * @return value of topic
	 */
	public final java.lang.String gettopic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.topic.toString());
	}

	/**
	 * Set value of topic
	 * @param topic
	 */
	public final void settopic(java.lang.String topic)
	{
		settopic(getContext(), topic);
	}

	/**
	 * Set value of topic
	 * @param context
	 * @param topic
	 */
	public final void settopic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String topic)
	{
		getMendixObject().setValue(context, MemberNames.topic.toString(), topic);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cdcSnapshotStoreMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.CdcSnapshotStore that = (system.proxies.CdcSnapshotStore) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
