// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

/**
 * Represents a Sub-Process as defined within a workflow model.
 */
public class WorkflowSubProcessDefinition implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowSubProcessDefinitionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.WorkflowSubProcessDefinition";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		IsObsolete("IsObsolete"),
		WorkflowSubProcessDefinition_WorkflowDefinition("System.WorkflowSubProcessDefinition_WorkflowDefinition");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowSubProcessDefinition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowSubProcessDefinition(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowSubProcessDefinitionMendixObject)
	{
		if (workflowSubProcessDefinitionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!workflowSubProcessDefinitionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowSubProcessDefinitionMendixObject = workflowSubProcessDefinitionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static system.proxies.WorkflowSubProcessDefinition initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.WorkflowSubProcessDefinition(context, mendixObject);
	}

	public static system.proxies.WorkflowSubProcessDefinition load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.WorkflowSubProcessDefinition.initialize(context, mendixObject);
	}

	public static java.util.List<system.proxies.WorkflowSubProcessDefinition> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> system.proxies.WorkflowSubProcessDefinition.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Caption
	 */
	public final java.lang.String getCaption()
	{
		return getCaption(getContext());
	}

	/**
	 * @param context
	 * @return value of Caption
	 */
	public final java.lang.String getCaption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Caption.toString());
	}

	/**
	 * Set value of Caption
	 * @param caption
	 */
	public final void setCaption(java.lang.String caption)
	{
		setCaption(getContext(), caption);
	}

	/**
	 * Set value of Caption
	 * @param context
	 * @param caption
	 */
	public final void setCaption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String caption)
	{
		getMendixObject().setValue(context, MemberNames.Caption.toString(), caption);
	}

	/**
	 * @return value of IsObsolete
	 */
	public final java.lang.Boolean getIsObsolete()
	{
		return getIsObsolete(getContext());
	}

	/**
	 * @param context
	 * @return value of IsObsolete
	 */
	public final java.lang.Boolean getIsObsolete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsObsolete.toString());
	}

	/**
	 * Set value of IsObsolete
	 * @param isobsolete
	 */
	public final void setIsObsolete(java.lang.Boolean isobsolete)
	{
		setIsObsolete(getContext(), isobsolete);
	}

	/**
	 * Set value of IsObsolete
	 * @param context
	 * @param isobsolete
	 */
	public final void setIsObsolete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isobsolete)
	{
		getMendixObject().setValue(context, MemberNames.IsObsolete.toString(), isobsolete);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowSubProcessDefinition_WorkflowDefinition
	 */
	public final system.proxies.WorkflowDefinition getWorkflowSubProcessDefinition_WorkflowDefinition() throws com.mendix.core.CoreException
	{
		return getWorkflowSubProcessDefinition_WorkflowDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowSubProcessDefinition_WorkflowDefinition
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowDefinition getWorkflowSubProcessDefinition_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowSubProcessDefinition_WorkflowDefinition.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowDefinition.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowSubProcessDefinition_WorkflowDefinition
	 * @param workflowsubprocessdefinition_workflowdefinition
	 */
	public final void setWorkflowSubProcessDefinition_WorkflowDefinition(system.proxies.WorkflowDefinition workflowsubprocessdefinition_workflowdefinition)
	{
		setWorkflowSubProcessDefinition_WorkflowDefinition(getContext(), workflowsubprocessdefinition_workflowdefinition);
	}

	/**
	 * Set value of WorkflowSubProcessDefinition_WorkflowDefinition
	 * @param context
	 * @param workflowsubprocessdefinition_workflowdefinition
	 */
	public final void setWorkflowSubProcessDefinition_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowDefinition workflowsubprocessdefinition_workflowdefinition)
	{
		if (workflowsubprocessdefinition_workflowdefinition == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowSubProcessDefinition_WorkflowDefinition.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowSubProcessDefinition_WorkflowDefinition.toString(), workflowsubprocessdefinition_workflowdefinition.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowSubProcessDefinitionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.WorkflowSubProcessDefinition that = (system.proxies.WorkflowSubProcessDefinition) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
