// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

/**
 * Representing the lifecycle states of an event sub-process.
 */
public enum WorkflowSubProcessState
{
	InProgress("3ff43bee-f45e-4a0e-9e90-2e06f9533d31"),
	Aborted("aec5abc6-861f-4648-8bc1-5f147281e593"),
	Failed("97903b7f-27a1-46c2-b37d-11e05636cd36"),
	Completed("f97c503c-29ea-488d-805f-8d3b1fcdeb71"),
	Paused("6982a73d-f70d-45ed-ae34-d5a9fd66078f");

	private final java.lang.String i18nCaptionKey;
	
	private WorkflowSubProcessState(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
