// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

/**
 * Represents an instance of an Event Sub-Process.
 */
public class WorkflowSubProcess implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowSubProcessMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.WorkflowSubProcess";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		State("State"),
		Reason("Reason"),
		WorkflowSubProcess_WorkflowSubProcessDefinition("System.WorkflowSubProcess_WorkflowSubProcessDefinition"),
		WorkflowSubProcess_Workflow("System.WorkflowSubProcess_Workflow");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowSubProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowSubProcess(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowSubProcessMendixObject)
	{
		if (workflowSubProcessMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!workflowSubProcessMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowSubProcessMendixObject = workflowSubProcessMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static system.proxies.WorkflowSubProcess initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.WorkflowSubProcess(context, mendixObject);
	}

	public static system.proxies.WorkflowSubProcess load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.WorkflowSubProcess.initialize(context, mendixObject);
	}

	public static java.util.List<system.proxies.WorkflowSubProcess> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> system.proxies.WorkflowSubProcess.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Caption
	 */
	public final java.lang.String getCaption()
	{
		return getCaption(getContext());
	}

	/**
	 * @param context
	 * @return value of Caption
	 */
	public final java.lang.String getCaption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Caption.toString());
	}

	/**
	 * Set value of Caption
	 * @param caption
	 */
	public final void setCaption(java.lang.String caption)
	{
		setCaption(getContext(), caption);
	}

	/**
	 * Set value of Caption
	 * @param context
	 * @param caption
	 */
	public final void setCaption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String caption)
	{
		getMendixObject().setValue(context, MemberNames.Caption.toString(), caption);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * Get value of State
	 * @param state
	 */
	public final system.proxies.WorkflowSubProcessState getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final system.proxies.WorkflowSubProcessState getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowSubProcessState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(system.proxies.WorkflowSubProcessState state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowSubProcessState state)
	{
		if (state != null) {
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
		}
	}

	/**
	 * @return value of Reason
	 */
	public final java.lang.String getReason()
	{
		return getReason(getContext());
	}

	/**
	 * @param context
	 * @return value of Reason
	 */
	public final java.lang.String getReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reason.toString());
	}

	/**
	 * Set value of Reason
	 * @param reason
	 */
	public final void setReason(java.lang.String reason)
	{
		setReason(getContext(), reason);
	}

	/**
	 * Set value of Reason
	 * @param context
	 * @param reason
	 */
	public final void setReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reason)
	{
		getMendixObject().setValue(context, MemberNames.Reason.toString(), reason);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowSubProcess_WorkflowSubProcessDefinition
	 */
	public final system.proxies.WorkflowSubProcessDefinition getWorkflowSubProcess_WorkflowSubProcessDefinition() throws com.mendix.core.CoreException
	{
		return getWorkflowSubProcess_WorkflowSubProcessDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowSubProcess_WorkflowSubProcessDefinition
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowSubProcessDefinition getWorkflowSubProcess_WorkflowSubProcessDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowSubProcessDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowSubProcess_WorkflowSubProcessDefinition.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowSubProcessDefinition.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowSubProcess_WorkflowSubProcessDefinition
	 * @param workflowsubprocess_workflowsubprocessdefinition
	 */
	public final void setWorkflowSubProcess_WorkflowSubProcessDefinition(system.proxies.WorkflowSubProcessDefinition workflowsubprocess_workflowsubprocessdefinition)
	{
		setWorkflowSubProcess_WorkflowSubProcessDefinition(getContext(), workflowsubprocess_workflowsubprocessdefinition);
	}

	/**
	 * Set value of WorkflowSubProcess_WorkflowSubProcessDefinition
	 * @param context
	 * @param workflowsubprocess_workflowsubprocessdefinition
	 */
	public final void setWorkflowSubProcess_WorkflowSubProcessDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowSubProcessDefinition workflowsubprocess_workflowsubprocessdefinition)
	{
		if (workflowsubprocess_workflowsubprocessdefinition == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowSubProcess_WorkflowSubProcessDefinition.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowSubProcess_WorkflowSubProcessDefinition.toString(), workflowsubprocess_workflowsubprocessdefinition.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowSubProcess_Workflow
	 */
	public final system.proxies.Workflow getWorkflowSubProcess_Workflow() throws com.mendix.core.CoreException
	{
		return getWorkflowSubProcess_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowSubProcess_Workflow
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Workflow getWorkflowSubProcess_Workflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Workflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowSubProcess_Workflow.toString());
		if (identifier != null) {
			result = system.proxies.Workflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowSubProcess_Workflow
	 * @param workflowsubprocess_workflow
	 */
	public final void setWorkflowSubProcess_Workflow(system.proxies.Workflow workflowsubprocess_workflow)
	{
		setWorkflowSubProcess_Workflow(getContext(), workflowsubprocess_workflow);
	}

	/**
	 * Set value of WorkflowSubProcess_Workflow
	 * @param context
	 * @param workflowsubprocess_workflow
	 */
	public final void setWorkflowSubProcess_Workflow(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Workflow workflowsubprocess_workflow)
	{
		if (workflowsubprocess_workflow == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowSubProcess_Workflow.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowSubProcess_Workflow.toString(), workflowsubprocess_workflow.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowSubProcessMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.WorkflowSubProcess that = (system.proxies.WorkflowSubProcess) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
