// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("faac649e-4fa2-4575-8c27-ff3c16a459cb"),
	startsWith("06cdddbc-03dd-4ba2-8181-819d8d9ac3cc"),
	endsWith("63af9e6e-23fa-4960-b5c9-1f7a1defa46e"),
	between("a36377b0-6f1a-4030-ba92-29322c3b348e"),
	greater("c7a38d81-cf0d-467d-a113-72209020c780"),
	greaterEqual("223a8c95-18f6-419f-9271-532883cdae30"),
	equal("8dd67cf4-b94f-409c-a84f-4b57ebe2aa11"),
	notEqual("ae587fdb-0a52-451d-9390-e26d50a4ef1c"),
	smaller("89cfa7c7-6207-4ea9-a4d9-f9723dd0d114"),
	smallerEqual("351b8151-751e-49d3-b7a3-5786fe4b1125"),
	empty("d4f2fae1-4955-4ccc-9918-89e8fbdd0098"),
	notEmpty("433c082e-b9dd-475c-90d6-e7c7e3386e9c");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
