// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("e72e92db-3e47-4c77-879b-a25ff5aa69ef"),
	startsWith("c5271ad7-22c3-44ff-85f4-a1eb4384bdae"),
	endsWith("9021b351-8d95-4b0d-bce3-5836172315fd"),
	between("01ca380f-872b-4f2d-9cd7-8ae998ee7b1b"),
	greater("838d0d74-a0d1-425a-b3f5-0edf2bf159a6"),
	greaterEqual("ea6be4f3-5dfc-4459-9e79-738c5f5fc185"),
	equal("4857039b-f2da-4c12-b03a-7b4fb56ba3d6"),
	notEqual("a8393620-bfbb-449c-af84-3c3f84bddce3"),
	smaller("0802d75a-0a3e-4bd2-aa39-4c61842b144b"),
	smallerEqual("882624b3-5508-45c2-b70f-3bfc70a5a16c"),
	empty("1c4e035c-af04-483d-8906-98d498685ad9"),
	notEmpty("b6e166d4-2528-42e0-8de8-862a387bc6b9");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
