// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("501fedab-7724-4585-9ace-b4bd114b2fe1"),
	startsWith("effcc1cc-38ed-448b-859f-51927381926c"),
	endsWith("d17c9fee-78dc-4667-acdb-c16258f2c72c"),
	between("481cc306-ec09-46ad-842f-314048856822"),
	greater("cd87d4f1-923f-473f-8152-5e51d2e56e42"),
	greaterEqual("61306599-ce5d-493d-aaec-4adab45e8da7"),
	equal("8619344a-6741-40db-82c6-5091331499e3"),
	notEqual("dd290e82-3c32-457a-a17e-028f30d55091"),
	smaller("1685fb69-249c-4c26-8195-e1d856acb63b"),
	smallerEqual("d19311ab-ac42-4ab2-8cb3-4701973096ee"),
	empty("692e76a4-d272-4b07-9de5-697b7ddd2afb"),
	notEmpty("96c66cac-5e65-4b62-91e9-4da7a75c6d5e");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
