// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("7a670726-7f77-4ab8-9412-d5ea8d884598"),
	denied("3dd8698d-7f10-4123-ad31-0f76f6b43a9d"),
	limited("15a3361f-a786-4db3-8c09-7b343b504196"),
	granted("f1a221c0-404f-4ce5-aa6d-aa6f399e62ce"),
	blocked("ed5b7291-c1bf-4e93-b864-f70025686efe");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
