// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("d9e376c9-4bac-43b2-b423-ddc22f8e876a"),
	denied("8a162615-96ad-4167-af4a-bdf0ed2a8d74"),
	limited("5db70b27-2f2b-41b7-af7d-36f6204e6f6c"),
	granted("351a351a-d1f7-4e6b-b2af-1ca2ac50d707"),
	blocked("1a8d0bc9-6601-4935-b859-95a5a8fb0726");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
