// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("ca38fcd6-5988-4209-93ad-92ca04ae1fff"),
	denied("43714394-26fd-4e7f-ad78-95111a4c6eb8"),
	limited("a7eb062f-7f57-4760-99bc-57c5edee8a28"),
	granted("1c46099e-ef1b-48ee-b2b3-8e97e17e4147"),
	blocked("0b1dded2-e7ef-4420-b70a-31be9ec4f440");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
