// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("2b0c1c32-5531-4ab8-857b-2ae935d6fde5"),
	low("2dffae02-63e7-41c8-b61d-2a3b6329a47b"),
	medium("3fabd312-1bc1-4991-bcce-9d5cce4e3732"),
	high("efa095c2-652f-4180-8365-ccb47b4647d7"),
	custom("f20b2d61-9c48-4569-b20d-fd22d73f3eb3");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
