// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("eb981926-9c61-48f1-bd92-70ac5a0314a1"),
	low("033137c9-e968-4bba-a6ab-b44deb05f376"),
	medium("fcdbdfc6-458a-4f03-91d7-c050f770d238"),
	high("811e216c-e247-47e7-a909-e50be67f0fca"),
	custom("18a852d5-0b78-4939-abcc-07ef71ee57ae");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
